version: "2"

services:
  
  frontend:
    build: ./client
    ports:
      - "4000:4000"
    environment:
      PORT: 4000
      REACT_APP_SERVER_URL: http://localhost:3000

  backend:
    build: ./server
    ports:
      - "3000:3000"